# Generated by Django 2.2.2 on 2019-06-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamNum', models.CharField(max_length=200)),
                ('TeamName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Did_They_Run', models.BooleanField(default=False)),
                ('Landing', models.BooleanField(default=False)),
                ('Sampling', models.BooleanField(default=False)),
                ('Claiming', models.BooleanField(default=False)),
                ('Park', models.BooleanField(default=False)),
                ('Gold_In_Cargo', models.IntegerField(default='0')),
                ('Silver_In_Cargo', models.IntegerField(default='0')),
                ('Depot', models.IntegerField(default='0')),
                ('How_Many_Seconds_Were_They_Broke', models.IntegerField(default='0')),
                ('Endgame', models.CharField(default='3', max_length=5)),
                ('Penalties', models.IntegerField(default='0')),
                ('Comments', models.CharField(default='lols', max_length=500)),
                ('info', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='scout.Info')),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='Team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scout.Team'),
        ),
    ]
