# Generated by Django 2.2.2 on 2019-06-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0003_team_teamnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='info',
            name='question_text',
        ),
    ]
